# Generated by Django 3.2.7 on 2021-09-01 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("inventory", models.IntegerField(default=20)),
                ("re_order_level", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Reorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("Proc", "Processed"), ("Pend", "Pending")],
                        default="Pend",
                        max_length=4,
                    ),
                ),
                ("reorder_date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="localstore.product",
                    ),
                ),
            ],
        ),
    ]
